/*
 * Copyright 2023-2026 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package util.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.artifacts.ExternalModuleDependency
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.FileTree
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Copy
import org.gradle.api.tasks.Exec
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.JavaExec
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.register
import org.gradle.kotlin.dsl.the
import org.gradle.work.DisableCachingByDefault
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import util.other.libs
import java.io.File

const val PROTOC_TESTING_CONFIGURATION = "protoc_internalTesting"
const val NPM_INSTALL_CONFORMANCE_TASK = "npmInstallConformance"
const val EJECT_CONFORMANCE_PROTOS_TASK = "ejectConformanceProtos"
const val UNZIP_PROTOBUF_CONFORMANCE_TASK = "unzipProtobufConformance"
const val WRITE_CONFORMANCE_EXECUTABLE_PATH_TASK = "writeConformanceExecutablePath"
const val PAYLOAD_PB = "payload.pb"
const val CONFORMANCE_PB = "conformance.pb"

private fun Project.getBinFrom(configuration: String): File {
    return configurations.getByName(configuration).map {
        zipTree(it).matching { include("bin/**") }.files.first()
    }.single()
}

private fun Project.getIncludeFrom(configuration: String): List<FileTree> {
    return configurations.getByName(configuration).map {
        zipTree(it).matching { include("include/**") }
    }
}

private fun List<String>.commonPrefix(): String {
    return fold(first()) { acc, s -> acc.commonPrefixWith(s) }
}

private fun Project.pbFile(name: String): File {
    return layout.buildDirectory.get()
        .dir("protobuf-conformance")
        .file(name)
        .asFile
        .apply {
            if (!exists()) {
                parentFile.mkdirs()
                createNewFile()
            }
        }
}

private fun Project.conformanceNpmDir(): File =
    layout.buildDirectory.get().dir("conformance-npm").asFile

private fun Project.conformanceEjectedProtosDir(): File =
    layout.buildDirectory.get().dir("conformance-protos").asFile

@DisableCachingByDefault(
    because = "Writes machine-specific absolute paths (conformance binary, build/, test source dir) " +
        "into a generated Kotlin source file; caching would either leak host paths across workers " +
        "or resolve to non-existent paths after restore."
)
abstract class ConformanceExecutablePathWriter : DefaultTask() {
    @get:Input
    abstract val outputDir: Property<File>

    @get:Input
    abstract val kotlinTestDir: Property<File>

    @get:InputFile
    abstract val executable: Property<File>

    @get:OutputFile
    abstract val destination: Property<File>

    @TaskAction
    fun action() {
        val dest = destination.get()
        if (dest.exists()) {
            dest.delete()
        }

        val parent = dest.parentFile
        if (!parent.exists()) {
            parent.mkdirs()
        }

        dest.writeText(
            """
            // file generated by ConformanceExecutablePathWriter task

            const val CONFORMANCE_EXECUTABLE_PATH: String = "${executable.get().absolutePath}"

            const val CONFORMANCE_OUTPUT_DIR: String = "${outputDir.get().absolutePath}"

            const val KOTLIN_TEST_DIR: String = "${kotlinTestDir.get().absolutePath}"

        """.trimIndent()
        )
    }
}

/**
 * Installs a pinned version of the `protobuf-conformance` npm package into [installDir].
 *
 * Cacheable because [conformanceVersion] is pinned against the `protobuf` version from the
 * catalog; in practice that yields a stable `node_modules/` tree for this package (transitive
 * deps are not lockfile-pinned under `--no-save`, but the conformance package's dep surface is
 * small and stable enough for caching to be safe). The full [installDir] is declared as the
 * output so that cache restore produces a working `node_modules/` (including the `.bin/` entry
 * points consumed by downstream tasks).
 *
 * [Exec.workingDir] is synced from [installDir] in [exec] so the cache key and the exec working
 * directory cannot drift.
 */
@CacheableTask
abstract class NpmInstallConformanceTask : Exec() {
    @get:Input
    abstract val conformanceVersion: Property<String>

    @get:OutputDirectory
    abstract val installDir: DirectoryProperty

    @TaskAction
    override fun exec() {
        val dir = installDir.get().asFile
        dir.mkdirs()
        workingDir = dir
        super.exec()
    }
}

/**
 * Runs the mock conformance client against the conformance test runner and captures the
 * generated failure lists under [outputDir].
 *
 * Declared inputs:
 * - [mockClientJar] — the compiled mock client JAR (content-based),
 * - [generatedProtoSources] — Buf-generated sources consumed by the client (name-based),
 * - [conformanceRunnerBin] — the pinned conformance runner binary (content-based),
 * - inherited `classpath` — `@Classpath` on [JavaExec].
 *
 * ### Cross-machine caching limitation
 *
 * This task is `@CacheableTask` so local incremental builds and fresh checkouts on the same
 * host get cache hits. Cross-machine cache hits are not achievable in practice: [classpath]
 * transitively includes the compiled output of `executable-paths.kt`, which embeds
 * machine-absolute paths from [ConformanceExecutablePathWriter]. The content-based
 * `@Classpath` fingerprint therefore differs between hosts. Resolving that would require
 * redesigning the runtime path lookup and is explicitly out of scope for KRPC-596.
 */
@CacheableTask
abstract class GenerateConformanceTestsTask : JavaExec() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val mockClientJar: RegularFileProperty

    // Name-only because the files come from a flat ListProperty<File> with no declared root —
    // RELATIVE would degrade to content-only anyway. Name + content is the meaningful key.
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val generatedProtoSources: ConfigurableFileCollection

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val conformanceRunnerBin: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    override fun exec() {
        args = listOf(mockClientJar.get().asFile.absolutePath)
        super.exec()
    }
}

@CacheableTask
abstract class GenerateConformanceFileDescriptorSet : Exec() {
    // Flat ListProperty<File> with no declared root — NAME_ONLY is the honest annotation:
    // RELATIVE would degrade to content-only here anyway. protoc's FileDescriptorSet output
    // only references the proto file paths as stripped by --proto_path, which the task
    // derives from the files' common prefix, so name + content is the meaningful cache key.
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val wktFilesCollection: ListProperty<File>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val conformanceFilesCollection: ListProperty<File>

    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val bin: Property<File>

    @get:OutputFile
    abstract val outputFile: Property<File>

    @TaskAction
    fun generate() {
        val wktFiles = wktFilesCollection.get().map { it.absolutePath }
        val conformanceFiles = conformanceFilesCollection.get().map { it.absolutePath }

        val wktProtoPath = if (wktFiles.isEmpty()) {
            emptyList()
        } else {
            listOf("--proto_path=${wktFiles.commonPrefix().substringBefore("/google/protobuf/")}")
        }

        val conformanceIncludeDir = conformanceFiles
            .commonPrefix()
            .substringBefore("/google/protobuf/")
            .substringBefore("/conformance/")

        val conformanceProtoPath = "--proto_path=$conformanceIncludeDir"

        commandLine(
            bin.get().absolutePath,
            *wktProtoPath.toTypedArray(),
            conformanceProtoPath,
            "-o", outputFile.get().absolutePath,
            *wktFiles.toTypedArray(),
            *conformanceFiles.toTypedArray(),
        )
    }
}

fun Project.setupProtobufConformanceResources() {
    val os = System.getProperty("os.name").lowercase()
    val osPart = when {
        os.startsWith("linux") -> "linux"
        os.startsWith("mac") -> "osx"
        else -> error("unsupported os for protobuf-conformance tests: $os")
    }

    val archPart = when (val arch = System.getProperty("os.arch").lowercase()) {
        in setOf("x86_64", "amd64", "aarch64") -> "x86_64"
        else -> error("unsupported arch for protobuf-conformance tests: $arch")
    }

    // Ivy repository for protoc binary from GitHub releases
    repositories.ivy {
        name = "github"
        url = uri("https://github.com")

        patternLayout {
            artifact("[organisation]/[module]/releases/download/v[revision]/[artifact]-[revision]-[classifier].[ext]")
        }

        metadataSources { artifact() }
    }

    configurations.create(PROTOC_TESTING_CONFIGURATION)

    dependencies {
        add(
            PROTOC_TESTING_CONFIGURATION,
            dependencies.create("protocolbuffers:protobuf:${libs.versions.protobuf.get().substringAfter(".")}").apply {
                this as ExternalModuleDependency
                artifact {
                    name = "protoc"
                    type = "zip"
                    extension = "zip"
                    classifier = "$osPart-$archPart"
                }
            },
        )
    }

    // Conformance test runner from npm: https://www.npmjs.com/package/protobuf-conformance
    val conformanceVersion = libs.versions.protobuf.get().substringAfter(".")
    val npmDir = conformanceNpmDir()
    val ejectedProtosDir = conformanceEjectedProtosDir()
    // Invoke the `.cjs` entry points directly rather than the `node_modules/.bin/…` symlinks.
    // Gradle's build cache dereferences symlinks on store and restores them as regular file
    // copies, which breaks node's require-resolution relative to the symlink location. Using
    // the real files keeps the dep graph intact across cache restore.
    val conformanceRunnerBin =
        File(npmDir, "node_modules/protobuf-conformance/conformance_test_runner.cjs")
    val conformanceProtoEjectBin =
        File(npmDir, "node_modules/protobuf-conformance/conformance_proto_eject.cjs")

    val npmInstallConformance = tasks.register<NpmInstallConformanceTask>(NPM_INSTALL_CONFORMANCE_TASK) {
        this.conformanceVersion.set(conformanceVersion)
        // The whole npmDir is the authoritative output — node_modules/ (including the transitive
        // dep graph) is produced by `npm install` and nothing else. Declaring only the
        // protobuf-conformance subdir would leave transitive deps out of any cache restore.
        installDir.set(npmDir)

        commandLine("npm", "install", "--no-save", "protobuf-conformance@$conformanceVersion.0")
    }

    val ejectConformanceProtos = tasks.register<Exec>(EJECT_CONFORMANCE_PROTOS_TASK) {
        dependsOn(npmInstallConformance)

        inputs.property("conformanceVersion", conformanceVersion)
        outputs.dir(ejectedProtosDir)

        commandLine(conformanceProtoEjectBin.absolutePath, ejectedProtosDir.absolutePath)

        doFirst {
            ejectedProtosDir.deleteRecursively()
        }
    }

    val unzipProtobufConformance = tasks.register<Copy>(UNZIP_PROTOBUF_CONFORMANCE_TASK) {
        dependsOn(ejectConformanceProtos)

        from(ejectedProtosDir)

        // Exclude protos with unsupported edition values
        exclude("**/test_messages_edition_unstable.proto")

        val destDir = project.layout.projectDirectory
            .dir("src")
            .dir("commonMain")
            .dir("proto")

        into(destDir)

        eachFile {
            path = "protobuf-conformance/$path"
        }

        includeEmptyDirs = false

        doFirst {
            destDir.asFile.deleteRecursively()
        }
    }

    tasks.register<GenerateConformanceFileDescriptorSet>("generateConformanceFileDescriptorSet_conformance") {
        dependsOn(ejectConformanceProtos)

        wktFilesCollection.set(emptyList())

        conformanceFilesCollection.set(
            provider {
                fileTree(ejectedProtosDir).matching { include("**/conformance.proto") }.files.toList()
            }
        )

        bin.set(getBinFrom(PROTOC_TESTING_CONFIGURATION))

        outputFile.set(project.pbFile(CONFORMANCE_PB))
    }

    tasks.register<GenerateConformanceFileDescriptorSet>("generateConformanceFileDescriptorSet_payload") {
        dependsOn(ejectConformanceProtos)

        val wktFiles = project.getIncludeFrom(PROTOC_TESTING_CONFIGURATION).flatMap { it.files }
        wktFilesCollection.set(wktFiles)

        conformanceFilesCollection.set(
            provider {
                fileTree(ejectedProtosDir).matching { include("**/test_messages_proto3.proto") }.files.toList()
            }
        )

        bin.set(getBinFrom(PROTOC_TESTING_CONFIGURATION))

        outputFile.set(project.pbFile(PAYLOAD_PB))
    }

    val writeConformanceExecutablePath =
        tasks.register<ConformanceExecutablePathWriter>(WRITE_CONFORMANCE_EXECUTABLE_PATH_TASK) {
            dependsOn(npmInstallConformance)

            outputDir.set(
                project.layout.buildDirectory.get()
                    .dir("protobuf-conformance")
                    .asFile
            )

            kotlinTestDir.set(
                project.layout.projectDirectory
                    .dir("src")
                    .dir("jvmTest")
                    .dir("kotlin")
                    .asFile
            )

            executable.set(conformanceRunnerBin)

            destination.set(
                project.layout.buildDirectory.get()
                    .dir("generated")
                    .dir("protobuf-conformance")
                    .file("executable-paths.kt")
                    .asFile
            )
        }

    // Proto processing tasks for all source sets need to depend on the proto extraction task
    tasks.matching { it.name.startsWith("process") && it.name.contains("ProtoFiles") }.all {
        dependsOn(unzipProtobufConformance)
    }

    the<KotlinMultiplatformExtension>().apply {
        sourceSets.getByName("jvmMain") {
            kotlin.srcDir(writeConformanceExecutablePath.map { it.destination.get().parentFile })
        }
    }
}
