#!/usr/bin/env bash
#
# Copyright 2023-2026 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
#
# Air cloud environment startup script for kotlinx-rpc.
#
# Runs in two modes, selected by the AIR_STARTUP_MODE environment variable:
#   warmup - snapshot-baking run: install toolchains, prime Gradle caches, then block on `healthcheck`.
#   task   - real task run: make sure the toolchain and shell hooks are in place and exit promptly.
#
# Everything installed here lives under $HOME (no sudo is available).

set -euo pipefail

if [ "${AIR_STARTUP_MODE:-}" = warmup ]; then WARMUP=1; else WARMUP=; fi

# The launch materializes this script outside the repository (e.g. /tmp/air-startup), so the
# repository root cannot be derived from the script location. Prefer an explicit override,
# then the current directory, then the standard workspace path.
find_repo_dir() {
    local candidate
    for candidate in "${KOTLINX_RPC_REPO_DIR:-}" "$PWD" /workspaces/kotlinx-rpc \
                     "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." 2>/dev/null && pwd)"; do
        if [ -n "$candidate" ] && [ -f "$candidate/settings.gradle.kts" ] && [ -f "$candidate/gradlew" ]; then
            printf '%s' "$candidate"
            return
        fi
    done
    echo "Cannot locate the kotlinx-rpc repository root (checked \$KOTLINX_RPC_REPO_DIR, \$PWD, /workspaces/kotlinx-rpc)" >&2
    exit 1
}
REPO_DIR="$(find_repo_dir)"
JDK_MAJOR=17
JDK_DIR="$HOME/.jdks/temurin-$JDK_MAJOR"
# Pinned fallback used when the Adoptium "latest" API is unreachable.
JDK_FALLBACK_URL="https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.20.1%2B1/OpenJDK17U-jdk_x64_linux_hotspot_17.0.20.1_1.tar.gz"
ENV_FILE="$HOME/.kotlinx-rpc-env.sh"
GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

log() { printf '[startup %s] %s\n' "$(date +%H:%M:%S)" "$*"; }

# ---------------------------------------------------------------------------
# JDK 17 (Temurin). The build's Gradle plugin and jpms-check pin a Java 17
# toolchain, and CI (GitHub ubuntu-latest) runs Gradle on 17 as well.
# ---------------------------------------------------------------------------
install_jdk() {
    if [ -x "$JDK_DIR/bin/java" ]; then
        log "JDK $JDK_MAJOR already present at $JDK_DIR"
        return
    fi
    local arch tmp
    case "$(uname -m)" in
        x86_64) arch=x64 ;;
        aarch64|arm64) arch=aarch64 ;;
        *) echo "Unsupported architecture: $(uname -m)" >&2; exit 1 ;;
    esac
    tmp="$(mktemp -d)"
    log "Downloading Temurin JDK $JDK_MAJOR ($arch)..."
    local latest="https://api.adoptium.net/v3/binary/latest/$JDK_MAJOR/ga/linux/$arch/jdk/hotspot/normal/eclipse"
    if ! curl -fsSL --retry 3 -o "$tmp/jdk.tar.gz" "$latest"; then
        log "Adoptium API unavailable, falling back to pinned release"
        if [ "$arch" != x64 ]; then
            echo "No pinned JDK fallback for $arch" >&2
            exit 1
        fi
        curl -fsSL --retry 3 -o "$tmp/jdk.tar.gz" "$JDK_FALLBACK_URL"
    fi
    mkdir -p "$JDK_DIR"
    tar -xzf "$tmp/jdk.tar.gz" -C "$JDK_DIR" --strip-components=1
    rm -rf "$tmp"
    "$JDK_DIR/bin/java" -version
    log "JDK $JDK_MAJOR installed to $JDK_DIR"
}

# ---------------------------------------------------------------------------
# Shell environment: JAVA_HOME/PATH must survive this script, so they go into a
# file sourced from the login-shell profile and from ~/.bashrc.
# ---------------------------------------------------------------------------
configure_shell_env() {
    cat > "$ENV_FILE" <<ENV
# Generated by .air/cloud/startup.sh (kotlinx-rpc). Sourced from the shell profile.
export JAVA_HOME="$JDK_DIR"
case ":\$PATH:" in
    *":\$JAVA_HOME/bin:"*) ;;
    *) export PATH="\$JAVA_HOME/bin:\$PATH" ;;
esac
ENV
    local marker='# kotlinx-rpc-air-env'
    local line="[ -f \"$ENV_FILE\" ] && . \"$ENV_FILE\" $marker"
    local profile=""
    for f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
        if [ -f "$f" ]; then profile="$f"; break; fi
    done
    [ -n "$profile" ] || { profile="$HOME/.profile"; touch "$profile"; }
    for f in "$profile" "$HOME/.bashrc"; do
        touch "$f"
        grep -qF "$marker" "$f" || printf '\n%s\n' "$line" >> "$f"
    done
    log "Shell hooks written to $profile and ~/.bashrc (env file: $ENV_FILE)"
}

# ---------------------------------------------------------------------------
# Gradle user properties: route JVM traffic through the sandbox egress proxy
# (Java does not read http_proxy env vars), skip Develocity build-scan
# publishing, and cap daemon heaps to fit the environment's RAM.
# ---------------------------------------------------------------------------
configure_gradle_properties() {
    mkdir -p "$GRADLE_USER_HOME"
    local props="$GRADLE_USER_HOME/gradle.properties"
    local begin='# >>> kotlinx-rpc air startup (managed block) >>>'
    local end='# <<< kotlinx-rpc air startup (managed block) <<<'
    local block
    block="$begin
kotlinx.rpc.develocity.skipBuildScans=true
kotlinx.rpc.develocity.skipGitTags=true
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:MaxMetaspaceSize=768m
kotlin.daemon.jvmargs=-Xmx5g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.installations.paths=$JDK_DIR"

    local proxy="${HTTPS_PROXY:-${https_proxy:-${HTTP_PROXY:-${http_proxy:-}}}}"
    if [ -n "$proxy" ]; then
        local hostport="${proxy#*://}"; hostport="${hostport%%/*}"; hostport="${hostport##*@}"
        local host="${hostport%%:*}" port="${hostport##*:}"
        [ "$port" = "$hostport" ] && port=80
        local nonproxy="localhost|127.0.0.1|::1"
        block="$block
systemProp.http.proxyHost=$host
systemProp.http.proxyPort=$port
systemProp.https.proxyHost=$host
systemProp.https.proxyPort=$port
systemProp.http.nonProxyHosts=$nonproxy
systemProp.https.nonProxyHosts=$nonproxy"
        log "Gradle JVM proxy configured: $host:$port"
    else
        log "No egress proxy in environment; Gradle will connect directly"
    fi
    block="$block
$end"

    touch "$props"
    # Replace an existing managed block, keep everything else untouched.
    awk -v b="$begin" -v e="$end" '
        $0 == b { skip = 1; next }
        $0 == e { skip = 0; next }
        !skip { print }
    ' "$props" > "$props.tmp"
    printf '%s\n' "$block" >> "$props.tmp"
    mv "$props.tmp" "$props"
    log "Gradle user properties written to $props"
}

# ---------------------------------------------------------------------------
# Gradle warm-up (WARMUP only): download the distribution, resolve dependencies,
# compile the JVM production and test classes of every module (including the
# compiler plugin, Gradle plugin and protoc-gen included builds).
# ---------------------------------------------------------------------------
gradle() {
    (cd "$REPO_DIR" && JAVA_HOME="$JDK_DIR" PATH="$JDK_DIR/bin:$PATH" ./gradlew --console=plain "$@")
}

warm_gradle() {
    log "Gradle: downloading distribution / printing version"
    gradle --version
    log "Gradle: compiling JVM main and test classes for all modules (this takes a while)"
    gradle jvmTestClasses
    log "Gradle: JVM warm-up finished"

    # Best effort: fetch the Kotlin/Native distribution + LLVM/sysroot dependencies and the
    # Kotlin/JS + Wasm compiler artifacts by compiling :core for one target of each kind. A failure
    # here only means a colder cache for non-JVM work, so it must not fail the startup.
    log "Gradle: priming Kotlin/Native, JS and Wasm toolchains via :core (best effort)"
    if gradle :core:compileKotlinLinuxX64 :core:compileKotlinJs :core:compileKotlinWasmJs --continue; then
        log "Gradle: non-JVM toolchain warm-up finished"
    else
        log "WARNING: non-JVM toolchain warm-up failed; continuing (JVM environment is unaffected)"
    fi
}

# ---------------------------------------------------------------------------
# healthcheck: prove the environment works the way a task needs it to — the
# JDK is usable, Gradle configures the whole composite build, and a real JVM
# test module compiles and passes.
# ---------------------------------------------------------------------------
healthcheck() {
    log "healthcheck: verifying JDK"
    "$JDK_DIR/bin/java" -version 2>&1 | head -1 | grep -q "\"$JDK_MAJOR\." \
        || { echo "healthcheck: JDK $JDK_MAJOR not usable at $JDK_DIR" >&2; return 1; }

    log "healthcheck: running JVM smoke tests (:utils:jvmTest :krpc:krpc-core:jvmTest)"
    local attempt=1
    until gradle :utils:jvmTest :krpc:krpc-core:jvmTest; do
        echo "healthcheck: smoke test attempt $attempt failed, retrying in 30s..." >&2
        attempt=$((attempt + 1))
        sleep 30
    done
    log "healthcheck: OK"
}

# ---------------------------------------------------------------------------
main() {
    log "kotlinx-rpc startup (mode: ${AIR_STARTUP_MODE:-unset}, repo: $REPO_DIR)"
    chmod +x "$REPO_DIR/gradlew" || true
    install_jdk
    configure_shell_env
    configure_gradle_properties

    if [ -n "$WARMUP" ]; then
        warm_gradle
        healthcheck
        log "Stopping Gradle daemons before snapshot"
        gradle --stop || true
    else
        log "Task mode: toolchain ready, skipping Gradle warm-up"
    fi
    log "startup finished"
}

main "$@"
