/*
 * Copyright 2023-2025 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

@file:Suppress("MemberVisibilityCanBePrivate")

package kotlinx.rpc.grpc

import kotlinx.rpc.internal.utils.InternalRpcApi

/**
 * Defines the status of an operation by providing a standard [GrpcStatusCode] in conjunction with an
 * optional descriptive message.
 *
 * For clients, every remote call will return a status on completion.
 * In the case of errors this
 * status may be propagated to blocking stubs as a [RuntimeException] or to a listener as an
 * explicit parameter.
 *
 * Similarly, servers can report a status by throwing [GrpcStatusException]
 * or by passing the status to a callback.
 *
 * Utility functions are provided to convert a status to an exception and to extract them
 * back out.
 *
 * Extended descriptions, including a list of codes that shouldn't be generated by the library,
 * can be found at
 * [doc/statuscodes.md](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md)
 */
public expect class GrpcStatus {
    internal fun getDescription(): String?
    internal fun getCause(): Throwable?
}

/**
 * Creates a [GrpcStatus] with the specified [code], optional [description], and [cause].
 */
public expect fun GrpcStatus(code: GrpcStatusCode, description: String? = null, cause: Throwable? = null): GrpcStatus

/**
 * The status code of this status.
 */
public expect val GrpcStatus.statusCode: GrpcStatusCode

/**
 * The description of this status, or null if not present.
 */
public val GrpcStatus.description: String? get() = getDescription()

// this is currently @InternalRpcApi as it's behavior would be inconsistent between JVM and Native.
@InternalRpcApi
public val GrpcStatus.cause: Throwable? get() = getCause()

/**
 * Converts this status to a [GrpcStatusException] with optional [trailers].
 */
public fun GrpcStatus.asException(trailers: GrpcMetadata? = null): GrpcStatusException {
    return GrpcStatusException(this, trailers)
}

/**
 * Standard gRPC status codes.
 */
public enum class GrpcStatusCode(public val value: Int) {
    OK(0),
    CANCELLED(1),
    UNKNOWN(2),
    INVALID_ARGUMENT(3),
    DEADLINE_EXCEEDED(4),
    NOT_FOUND(5),
    ALREADY_EXISTS(6),
    PERMISSION_DENIED(7),
    RESOURCE_EXHAUSTED(8),
    FAILED_PRECONDITION(9),
    ABORTED(10),
    OUT_OF_RANGE(11),
    UNIMPLEMENTED(12),
    INTERNAL(13),
    UNAVAILABLE(14),
    DATA_LOSS(15),
    UNAUTHENTICATED(16);

    /**
     * The ASCII-encoded byte representation of the status code value.
     */
    public val valueAscii: ByteArray = value.toString().encodeToByteArray()

    /**
     * Converts this status code to a [GrpcStatus] with an optional [description].
     */
    public fun asStatus(description: String? = null): GrpcStatus {
        return GrpcStatus(this, description)
    }

    /**
     * Converts this status code to a [GrpcStatusException] with optional [description] and [trailers].
     */
    public fun asException(description: String? = null, trailers: GrpcMetadata? = null): GrpcStatusException {
        return GrpcStatusException(GrpcStatus(this, description), trailers)
    }
}
