/*
 * Copyright 2023-2026 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package kotlinx.rpc.buf.tasks

import kotlinx.rpc.protoc.ProtoTask
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskProvider
import java.io.File
import javax.inject.Inject

/**
 * Buf `dep update` command or copies existing `buf.lock` file.
 *
 * @see <a href="https://buf.build/docs/reference/cli/buf/dep/update/">buf dep update</a>
 */
public abstract class BufLockTask @Inject internal constructor(
    properties: ProtoTask.Properties,
) : BufExecTask(properties) {
    init {
        command.convention("dep")
        args.convention(listOf("update"))

        bufLockFile.convention(project.layout.file(workingDir.map { it.resolve("buf.lock") }))
        persistentLockFile.convention(project.layout.projectDirectory.file(persistentLockFilePath))

        onlyIf { bsrDeps.get().isNotEmpty() }
    }

    /**
     * Declared BSR modules. If empty, this tasks is skipped.
     */
    @get:Input
    public abstract val bsrDeps: ListProperty<String>

    /**
     * Path to the persistent `buf.lock` file location. 
     */
    @get:Input
    public abstract val persistentLockFilePath: Property<String>

    /**
     * The persistent `buf.lock` file that caches dependency information across builds.
     * Synchronized with [bufLockFile] during task execution.
     */
    @get:OutputFile
    public abstract val persistentLockFile: RegularFileProperty

    /**
     * The working `buf.lock` file in the build output directory. Generated by `buf dep update`
     * or copied from [persistentLockFile] if it exists.
     */
    @get:OutputFile
    public abstract val bufLockFile: RegularFileProperty

    override fun exec() {
        val persistentLock = persistentLockFile.orNull?.asFile ?: return
        if (persistentLock.exists()) {
            persistentLock.copyTo(bufLockFile.get().asFile, overwrite = true)
        } else {
            super.exec()

            val generated = bufLockFile.get().asFile
            if (!generated.exists()) return

            persistentLock.parentFile?.mkdirs()
            generated.copyTo(persistentLock)
        }
    }

    internal companion object {
        const val NAME_PREFIX: String = "bufLock"
    }
}

internal fun Project.registerBufLockTask(
    name: String,
    workingDir: File,
    bsrDependencies: Provider<List<String>>,
    properties: ProtoTask.Properties,
    lockFile: Property<String>,
    configure: BufLockTask.() -> Unit = {},
): TaskProvider<BufLockTask> {
    return registerBufExecTask(BufLockTask::class, "${BufLockTask.NAME_PREFIX}$name", provider { workingDir }, properties) {
        bsrDeps.convention(bsrDependencies)
        persistentLockFilePath.convention(lockFile)

        configure()
    }
}