package org.jetbrains.krpc.client

import org.jetbrains.krpc.RPC

/**
 * Waits for the initialization of an RPC field in the generated client:
 * ```kotlin
 * interface MyService : RPC {
 *     val stateFlow: StateFlow<Int>
 * }
 *
 * val client = RPC.clientOf<MyService>(transport)
 * val currentValue = client.awaitFieldInitialization { stateFlow }.value
 * ```
 */
suspend fun <T : RPC, R> T.awaitFieldInitialization(getter: T.() -> R): R {
    val field = getter()

    if (field is RPCProperty<*>) {
        @Suppress("UNCHECKED_CAST")
        return (field as RPCProperty<R>).await()
    }

    error("Please choose required field for a valid RPC client generated by a RPC.clientOf method")
}
