#!/usr/bin/env bash
#
# Copyright 2023-2025 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
#

: "${KONAN_HOME:?KONAN_HOME must be set}"

TOOL_NAME="$1"
shift

if [ -z "$JAVACMD" -a -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD=java
fi
[ -n "$JAVACMD" ] || JAVACMD=java

declare -a java_args
declare -a java_opts
declare -a konan_args

pass_rest=false
while [ $# -gt 0 ]; do
  if [ "$pass_rest" = true ]; then
    konan_args+=("$1")
    shift
    continue
  fi

  case "$1" in
    --)
      pass_rest=true
      shift
      ;;
    -D*)
      java_args+=("$1")
      shift
      ;;
    -J*)
      java_args+=("${1:2}")
      shift
      ;;
    --time)
      konan_args+=("--time")
      java_args+=("-Dkonan.profile=true")
      TIMECMD=time
      shift
      ;;
    *)
      konan_args+=("$1")
      shift
      ;;
  esac
done

java_opts=(-ea \
            -Xmx3G \
            -XX:TieredStopAtLevel=1 \
            -Dfile.encoding=UTF-8 \
            -Dkonan.home="$KONAN_HOME" \
            ${JAVA_OPTS})

# Unset some environment variables which are set by XCode and may potentially affect the tool executed.
while IFS=$'\r' read -r line || [[ -n "$line" ]]; do
    unset $line
done < "${KONAN_HOME}/tools/env_blacklist"

KONAN_JAR="${KONAN_HOME}/konan/lib/kotlin-native-compiler-embeddable.jar"
KONAN_CLASSPATH="$KONAN_JAR"
TOOL_CLASS=org.jetbrains.kotlin.cli.utilities.MainKt
LIBCLANG_DISABLE_CRASH_RECOVERY=1 \
$TIMECMD "$JAVACMD" "${java_opts[@]}" "${java_args[@]}" -cp "$KONAN_CLASSPATH" "$TOOL_CLASS" "$TOOL_NAME" "${konan_args[@]}"