/*
 * Copyright 2023-2024 JetBrains s.r.o and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package kotlinx.rpc.internal

import kotlinx.rpc.internal.utils.InternalRpcApi

@InternalRpcApi
public inline fun <reified T> Any?.dataCast(methodName: String, serviceName: String): T {
    return this as? T
        ?: throw IllegalArgumentException(
            "Wrong data type for $methodName in service $serviceName. " +
                    "Please, provide only data that is generated by the service " +
                    "and passed in RpcCall.data, or deserialized version of this data."
        )
}
