

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("src/testData/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("customParameterTypes.kt")
  public void testCustomParameterTypes() {
    run("customParameterTypes.kt");
  }

  @Test
  @TestMetadata("flowParameter.kt")
  public void testFlowParameter() {
    run("flowParameter.kt");
  }

  @Test
  @TestMetadata("grpc.kt")
  public void testGrpc() {
    run("grpc.kt");
  }

  @Test
  @TestMetadata("multiModule.kt")
  public void testMultiModule() {
    run("multiModule.kt");
  }

  @Test
  @TestMetadata("protoMessage.kt")
  public void testProtoMessage() {
    run("protoMessage.kt");
  }

  @Test
  @TestMetadata("serviceDescriptor.kt")
  public void testServiceDescriptor() {
    run("serviceDescriptor.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    run("simple.kt");
  }
}
