

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  private void run(String fileName) {
    runTest("src/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("checkedAnnotation.kt")
  public void testCheckedAnnotation() {
    run("checkedAnnotation.kt");
  }

  @Test
  @TestMetadata("rpcChecked.kt")
  public void testRpcChecked() {
    run("rpcChecked.kt");
  }

  @Test
  @TestMetadata("rpcService.kt")
  public void testRpcService() {
    run("rpcService.kt");
  }

  @Test
  @TestMetadata("strictMode.kt")
  public void testStrictMode() {
    run("strictMode.kt");
  }
}
