name: Verify Docs Changelog

on:
  pull_request:

permissions:
  contents: read

jobs:
  verify-platforms-table:
    name: Run Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check Platforms Table
        run: ./gradlew updateDocsChangelog --info --stacktrace

      - name: Check if changelog is up-to-date
        run: |
          if [[ -n "$(git status --porcelain | grep docs/pages/kotlinx-rpc/topics/changelog.md)" ]]; then
            echo "Changelog is not up to date. Please run './gradlew updateDocsChangelog' and commit changes"
            exit 1
          fi
