name: Store Dokka Artifact

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of library that is being documented'
        required: true
        type: string
      buildId:
        description: 'TeamCity build id'
        required: true
        type: string
      artifactName:
        description: 'Name of artifact to download'
        required: true
        type: string

jobs:
  store-dokka-artifact:
    name: Store Dokka Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download Dokka artifact
        run: |
          curl -v -s -f -L \
            -H "Authorization: Bearer ${{ secrets.TEAMCITY_TOKEN }}" \
            https://krpc.teamcity.com/app/rest/builds/id:${{ inputs.buildId }}/artifacts/content/${{ inputs.artifactName }} -o dokka.zip
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: dokka-${{ inputs.version }}
          path: dokka.zip
          retention-days: 21
